LOAD DATA LOCAL INFILE '/Users/micheleluigigreco/Desktop/users.csv'
 INTO TABLE USERS
 FIELDS TERMINATED BY ','
 (ID,USERNAME,PSW,EMAIL,NAME,SURNAME,IMAGE,REGISTRATION_DATE);

 LOAD DATA LOCAL INFILE '/Users/micheleluigigreco/Desktop/file_owners.csv'
 INTO TABLE FILE_OWNERS
 FIELDS TERMINATED BY ','
 (ID,FILENAME,PATH);
 